feat: Creat some first routes
spirabr/backend pull request #27
Opened 2020-10-17 22:39 UTC by MattConce

Signed-off-by: Matheus Santos <mattsantos.conce@gmail.com>
Signed-off-by: Ricardo Kojo <ricardokojo7@gmail.com>
Signed-off-by: Vinicius Pereira <vini.gpereira2014@gmail.com>

closes #24

2020-10-20 17:31 UTC, AlexiaScheffer submitted a review, later dismissed

2020-10-20 18:28 UTC, victorhmp requested changes

2020-10-20 18:28 UTC, victorhmp commented on src/routes/routes.js
> +  res.json({data:response});
⛏️ [Nitpick]
```suggestion

  res.json({data:response});
```

2020-10-20 18:28 UTC, victorhmp commented on src/routes/routes.js
> +  res.json({data:response});
```suggestion
  const cpf = req.params.cpf
  
  const response = await req.dbConnection
    .collection("records")
    .findOne({cpf});
    
  res.json({data:response});
```

2020-10-21 14:52 UTC, victorhmp approved these changes

2020-10-22 14:36 UTC, AlexiaScheffer approved these changes

2020-10-22 14:36 UTC, merged