feat: Create first routes, completion of the missing routes
spirabr/backend pull request #29
Opened 2020-10-29 01:11 UTC by MattConce

Signed-off-by: Matheus Santos <mattsantos.conce@gmail.com>

2020-10-29 20:10 UTC, ricardokojo requested changes

2020-10-29 20:10 UTC, ricardokojo commented on package.json
> +    "body-parser": "*"
É bom deixar uma versao fixa da dependência, para não ficar atualizando toda hora

2020-10-29 20:10 UTC, ricardokojo commented on src/test.sh
> +printf "POST: create new user \n"
Para criar os testes, é melhor usar o Jest mesmo

2020-10-29 20:10 UTC, ricardokojo commented on src/routes/routes.js
> +  const user = {name: req.body.name, cpf: req.body.cpf, email: req.body.email,
Quebrar linhas

2020-10-29 20:10 UTC, ricardokojo commented on src/routes/routes.js
> +        {$set: {"email": email}}, {upsert: true});
Atualizar outros dados também

2020-10-29 20:10 UTC, ricardokojo commented on src/routes/routes.js
> +    console.log(cpf);
Remover console.log

2020-10-29 20:44 UTC, MattConce commented on src/test.sh
> +printf "POST: create new user \n"
Isso foi só para mostrar o que eu tinha testado mesmo. Tira do commit esse arquivo?

2020-10-29 21:54 UTC, AlexiaScheffer submitted a review, later dismissed

2020-10-31 16:57 UTC, MattConce commented
Fiz um rebase pra tirar o commit antigo, @AlexiaScheffer precisa revisar outra vez poque acabou dando dismissed

2020-11-03 18:13 UTC, ricardokojo approved these changes

2020-11-03 18:50 UTC, AlexiaScheffer approved these changes

2020-11-05 17:11 UTC, merged