Add documentation.
spirabr/backend pull request #38
Opened 2020-11-28 22:41 UTC by AlexiaScheffer

Closes #35 

Co-authored-by: Alexia Scheffer <ac.scheffer@usp.br>
Co-authored-by: Victor Miranda <victor2142@gmail.com>

2020-11-30 00:36 UTC, ricardokojo requested changes
Acho que faltam alguns pontos importantes:

- Falar sobre o NodeJS;
- Explicar como rodar sem Docker (`node app.js`);
- Falar sobre MongoDB, e explicitar que ao subir com Docker Compose um container com Mongo sobe na porta `27017`;
- Explicitar que a aplicação sobe na porta `3000`;
- Dar exemplos de como testar a aplicação, e exemplos de requests a serem feitas.

2020-12-01 23:16 UTC, ricardokojo approved these changes, later dismissed

2020-12-03 19:48 UTC, vini-gpereira commented on README.md
> +| DELETE | `/:patientId` | Deleta uma coleta do paciente com ID igual a `patientId`.               |
Será que não é interessante colocar um **schema** de uma coleta, pelo menos o inicial que temos hoje?

2020-12-03 20:20 UTC, vini-gpereira approved these changes

2020-12-03 21:13 UTC, ricardokojo approved these changes

2020-12-05 15:20 UTC, merged