Feat/create start npm script
spirabr/backend pull request #41
Opened 2020-12-05 21:37 UTC by ricardokojo

Closes #28

2020-12-06 19:09 UTC, wanderdasouza approved these changes

2020-12-07 21:01 UTC, victorhmp requested changes

2020-12-07 21:01 UTC, victorhmp commented on package.json
> +    "start": "node build/app.js",
O `build` tem q ser chamado antes. Isso está configurado no Heroku?

2020-12-08 13:29 UTC, ricardokojo commented on package.json
> +    "start": "node build/app.js",
Sim, o Heroku faz isso por padrão (meio obscuro, mas está na documentação 😓 )

2020-12-08 18:40 UTC, ThaisLasso approved these changes

2020-12-08 18:44 UTC, vini-gpereira approved these changes

2020-12-08 18:44 UTC, merged