Feat/testing day
spirabr/backend pull request #43
Opened 2020-12-10 21:10 UTC by ThaisLasso

Closes #37.

2020-12-12 21:39 UTC, AlexiaScheffer approved these changes, later dismissed

2020-12-12 23:10 UTC, MattConce approved these changes, later dismissed

2020-12-12 23:40 UTC, AlexiaScheffer approved these changes, later dismissed

2020-12-12 23:53 UTC, ricardokojo requested changes

2020-12-12 23:53 UTC, ricardokojo commented on src/modules/validate.js
> +}
Faltou a linha em branco aqui 😅

2020-12-13 00:12 UTC, ricardokojo approved these changes

2021-02-21 17:41 UTC, merged